include: [".md"]

markdown: kramdown
kramdown:
  input: GFM                    # Forces GitHub Flavored Markdown (tables, strikethrough, etc.)
  auto_ids: true                # Automatically creates id="open-data-sources" for headers
  smart_quotes: ["lsquo", "rsquo", "ldquo", "rdquo"] # Replaces your "SMART" option